CREATE TABLE EMPLOYEE ( 
    Fname 
    Minit 
    Lname 
    Ssn
    Bdate 
    Address Sex
    Salary
    Super_ssn Dno
    PRIMARY KEY (Ssn),
);

CREATE TABLE DEPARTMENT ( Dname Dnumber Mgr_ssn
Mgr_start_date
CREATE TABLE DEPT_LOCATIONS ( Dnumber Dlocation
CREATE TABLE PROJECT ( Pname Pnumber Plocation Dnum
VARCHAR(15) INT
CHAR(9) DATE,
PRIMARY KEY (Dnumber), UNIQUE (Dname), FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn) );
INT VARCHAR(15)
NOT NULL, NOT NULL,
PRIMARY KEY (Dnumber, Dlocation), FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber) );
VARCHAR(15) INT
VARCHAR(15), INT
PRIMARY KEY (Pnumber), UNIQUE (Pname), FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber) );
CREATE TABLE WORKS_ON ( Essn Pno
Hours
CHAR(9) INT
DECIMAL(3,1)
PRIMARY KEY (Essn, Pno), FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn), FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber) );
CREATE TABLE DEPENDENT ( Essn
Dependent_name Sex
Bdate Relationship CHAR(9)
VARCHAR(15) CHAR, DATE,
VARCHAR(8),
PRIMARY KEY (Essn, Dependent_name), FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn) );
NOT NULL, NOT NULL,
NOT NULL, NOT NULL, NOT NULL,
NOT NULL, NOT NULL,
NOT NULL,
NOT NULL, NOT NULL, NOT NULL,
VARCHAR(15) CHAR,
VARCHAR(15) CHAR(9) DATE,
VARCHAR(30), CHAR,
DECIMAL(10,2), CHAR(9), INT
NOT NULL, NOT NULL,
NOT NULL, NOT NULL,